apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: metapod-overwritepolicy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: metapod
      namespace: demo
  overrideRules:
    - targetCluster:
        clusterNames:
          - cluster1
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/9/CLUSTER_NAME
            operator: replace
            value: cluster1
    - targetCluster:
        clusterNames:
          - cluster2
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/9/CLUSTER_NAME
            operator: replace
            value: cluster2
    - targetCluster:
        clusterNames:
          - cluster3
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/9/CLUSTER_NAME
            operator: replace
            value: cluster3
